version: '3.7'

services:
  mysqldb:  
    image: mysql:5.7
    container_name: mysqldb
    hostname: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=appdb
      - MYSQL_USER=user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  applaravel:
    build: .
    container_name: applaravel
    hostname: applaravel
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysqldb

secrets:
  db_root_password:
    file: db_root_password.txt
  db_password:
    file: db_password.txt

volumes:
  mysql-data:

networks:
  default:
